### ISSUE TITLE
Introduce a state management library

### ISSUE THREAD

**Issue by Green-Ranger11** [MLH-Fellowship/gitdash#15]
At the moment, we are not using a state management library. A useful example would be issue #12 where we would have to use props to pass values from login to navbar to show the login state. A better way would be to use a state management library such as Mob x

**Comment by anandrajaram21** [comment]
Trying to refactor code to use MobX now might introduce a lot of breaking changes. So this will not be worked on, and instead other more important issues will be taken care of.
