### ISSUE TITLE
JWT does not have details about the current user's username

### ISSUE THREAD

**Issue by anandrajaram21** [MLH-Fellowship/gitdash#27]
Need to figure out a way to get the username of the currently signed in user.

**Comment by anandrajaram21** [comment]
I think what could be done to fix the issue is to make another API request to get the username using this:
![image](https://user-images.githubusercontent.com/48560219/127728064-6768cc29-bae1-46ad-b2d3-e76f18274058.png)
The screenshot is from the documentation of the octokit rest.js client

**Comment by Green-Ranger11** [comment]
Yeah only issue I see is sometimes user's don't allow applications access to their email so the jwt comes back with a null email

**Comment by Green-Ranger11** [comment]
Actually we can pass the authorization to the `Get User` endpoint on github api to get that info I believe. [Info here](https://docs.github.com/en/rest/reference/users)

Once the user is authorized we can use the [getToken](https://next-auth.js.org/tutorials/securing-pages-and-api-routes) method from NextJs and use that to authenticate with the github api.

**Comment by anandrajaram21** [comment]
@Green-Ranger11 This issue is linked to #17. As #17  has been resolved, I'll close this too
