### ISSUE TITLE
Refactor code to use @octokit/core instead of @octokit/rest

### ISSUE THREAD

**Issue by anandrajaram21** [MLH-Fellowship/gitdash#39]
@octokit/rest is redundant as @octokit/core has a lot more features and can do whatever @octokit/rest can do, but better.

**Comment by prakharrathi25** [comment]
I can work on this one since I am dealing with Octokit APIs at the moment.

**Comment by anandrajaram21** [comment]
Absolutely, go for it

**Comment by anandrajaram21** [comment]
This issue has been fixed now.
