### ISSUE TITLE
Main and Staging different git histories

### ISSUE THREAD

**Issue by Green-Ranger11** [MLH-Fellowship/gitdash#4]
Main and staging have different git histories and this needs to be resolved before we move further.

**Comment by prakharrathi25** [comment]
I think if you branch for staging then people are not running into this error, not sure though.

**Comment by Green-Ranger11** [comment]
Yeah totally agree. Just worried incase we have to merge into main at the end of the week and run into some errors.

**Comment by Green-Ranger11** [comment]
So after some discussion before standup, this will only become an issue if you mistakenly branch off staging. Closing this now.

**Comment by Green-Ranger11** [comment]
My bad, I see that @robzwolf opened a branch for this and will leave this open.

**Comment by Green-Ranger11** [comment]
Hi @robzwolf This is the issue as per what you mentioned in the standup. Can't PR into main.
