### ISSUE TITLE
The number of repos that we have starred is wrong

### ISSUE THREAD

**Issue by anandrajaram21** [MLH-Fellowship/gitdash#44]
The number of repos that the user has starred shows up as 100, if the number is more than 100 because of the `per_page=100`in the GET request URL

![image](https://user-images.githubusercontent.com/48560219/128007185-f68b5f92-e6ca-4af9-84b9-ea5d5eee8ceb.png)

**Comment by Green-Ranger11** [comment]
I can get to work on this. I believe the user details contains total stars?
