### ISSUE TITLE
Create models folder & helpers/extension folders

### ISSUE THREAD

**Issue by Green-Ranger11** [MLH-Fellowship/gitdash#46]
To make full use of intellisense and typescript we should have a separate folder for models. For example we this could refactor our github.ts page.

In addition, this is optional but coming from C# the github.ts file is getting too big for my liking and was wondering if we could also include a helpers folder as well as extension folders depending on whether it makes sense with NextJs. Can be either both, one or the other or neither of them.

### This is way too long for a parameter
![toolong](https://user-images.githubusercontent.com/39209557/128093554-ef2dfcf9-8aff-4a96-b85b-a89c74c7ed07.PNG)

@anandrajaram21 Could you please set this up since you set up the folder structure.

**Comment by anandrajaram21** [comment]
@Green-Ranger11 I'll be making this a low priority issue, as there are a lot more features that are yet to be added, which are more important than this.
