### ISSUE TITLE
Add more data to the dashboard

### ISSUE THREAD

**Issue by anandrajaram21** [MLH-Fellowship/gitdash#49]
Right now, the dashboard has data that is pretty much not useful to anyone (this data was there in place only for the MVP). We should get the actionable data onto the dashboard, and make the dashboard look better.

**Comment by prakharrathi25** [comment]
What actionable data do you want to add? Let's discuss that

**Comment by anandrajaram21** [comment]
Oh wait, what I meant by that was to get the issue and pull request data onto the dashboard. Its directly related to #52

**Comment by prakharrathi25** [comment]
Oh ok, fair enough.
