### ISSUE TITLE
Set up Github Projects

### ISSUE THREAD

**Issue by Green-Ranger11** [MLH-Fellowship/gitdash#5]
We need a way to be able to track our progress as well and help manage our tasks. Github Projects has really improved over the past year.

**Comment by Green-Ranger11** [comment]
Will get to work on this after I complete issue #6 unless anyone else wants to take this.

**Comment by prakharrathi25** [comment]
I can look at this one.

**Comment by prakharrathi25** [comment]
I have created the board and add all of you as collaborators.
