### ISSUE TITLE
Return issues and PRs from repositories that the user is not an owner of

### ISSUE THREAD

**Issue by anandrajaram21** [MLH-Fellowship/gitdash#66]
Right now, we are only returning the issues and PRs from repositories that the user owns. This may not always be the case, and as a result, users might miss out on some important information.

**Comment by Green-Ranger11** [comment]
I can also help look into this!

**Comment by Green-Ranger11** [comment]
I believe for organizational repositories you actually have to request for access to this information. I will look into other repositories that the user is not the owner of.

**Comment by Green-Ranger11** [comment]
Okay we can get repos that the user is a contributor to but cannot get access to organizational repos. That requires the user requesting for access and I don't think there is a work around.

![d](https://user-images.githubusercontent.com/39209557/128676390-363eed89-a9b0-47c6-a7d2-75ae9a5a69ad.PNG)

**Comment by anandrajaram21** [comment]
This is amazing work. I've seen similar looking requests on other websites too. As you said @Green-Ranger11, I think there is nothing we can do about that.
