### ISSUE TITLE
Styling conventions

### ISSUE THREAD

**Issue by Green-Ranger11** [MLH-Fellowship/gitdash#70]
Have just gone through code freeze 2 and thinking we should adhere to a certain style guide or adding a linter since we're a little inconsistent across the codebase. Some of the things Robbie mentioned:
- We're sometimes using semi-colons.
- We could go with template strings more often!

In general, this is to keep our code looking nice and clean!

**Comment by anandrajaram21** [comment]
I absolutely agree. But we are near the end, so maybe its an improvement for later?
