### ISSUE TITLE
Separate Issues & PR page

### ISSUE THREAD

**Issue by Green-Ranger11** [MLH-Fellowship/gitdash#71]
I know we discussed having PRs and issues page on the dashboard but was thinking maybe we COULD have separate page for PRs and Issues but this time having more information like a total count of issues and have filters for which repos have different PRs and issues.

**Comment by prakharrathi25** [comment]
I am not sure about this. Couldn't they view this on Github per repo as well? How do we add value beyond github? 
What sort of filters could we add?

**Comment by Green-Ranger11** [comment]
Like we could add a filter to only show issues and PRs for certain repositories. We could do a filter to show the oldest issues and PRs, we could filter to show which issues we manually assigned to ourselves and which issues were assigned by another user. We could show the total number of issues and PRs assigned to a user. It's just an idea since all we are showing at the moment are ALL the PRs and issues assigned to a user.

All in all, its just an idea. I do agree we could do with just the dashboard page but am open to suggestions or we could even move the filters to the dashboard.

**Comment by prakharrathi25** [comment]
We could do oldest and most recent repos for sure, maybe we could add those as additional features when we are done with the overall application?

**Comment by Green-Ranger11** [comment]
Yeah that's a good point. We only have a week left and we should focus on what we already have. Anyways I will close this issue. Thanks for the constructive discussion!
