### ISSUE TITLE
Add a new repositories page and favourites page

### ISSUE THREAD

**Issue by anandrajaram21** [MLH-Fellowship/gitdash#79]
Add a new page where users can get a list of repositories that they have contributed to and favourite some repositories too.

**Comment by prakharrathi25** [comment]
Is this only from UI perspective because I am working on the API endpoint for this?

**Comment by prakharrathi25** [comment]
The pull request #81 basically does this so you can just work on the UI for it now. Alesana is working on implementing the API for the Cockroach DB.

**Comment by anandrajaram21** [comment]
Yup, it's only from the UI perspective
I'm working on it rn

**Comment by prakharrathi25** [comment]
Sounds good!
